### PR TITLE
feat: Add GCP BYOC vendor access module

### PR DESCRIPTION
**Pull request by ciiiii**
```hcl
provider "google" {
  project = "<YOUR_PROJECT>"
}
module "sn_managed_cloud" {
  source = "github.com/streamnative/terraform-managed-cloud//modules/google/vendor-access?ref=v3.7.0"
  project = "<YOUR_PROJECT>"
}
```

### CODE REVIEW

**Comment by yuweisung** [comment]
Can this handle impersonation? 
https://cloud.google.com/docs/authentication/use-service-account-impersonation

**Comment by ciiiii** [comment]
> Can this handle impersonation?

Not yet, impersonation is still WIP

**Comment by yuweisung** [comment]
REF: https://cloud.google.com/blog/topics/developers-practitioners/using-google-cloud-service-account-impersonation-your-terraform-code

**Review by illegalnumbers — CHANGES_REQUESTED** [review]
you are not supposed to grant direct access to the account except for pool automation and cloud-manager. the human access needs to be done via impersonating the gsa already created in their account. standardize that gsa name in the terraform-gcp-cloud module and add it here

**Review by illegalnumbers — APPROVED** [review]
I talked to Sean. He didn't communicate this very well.

**Review by sijie — APPROVED** [review]

**Pull request merged**
